### ISSUE TITLE
Filtration time

### ISSUE THREAD

**Issue by mycanaletto** [oncleben31/ha-pool_pump#11]
Hello,
There's something I don't understand.
For a water temperature of 23/24°, we should filter according to the °C/2 rule, but filtering in auto mode only gives 8 hours...

**Comment by oncleben31** [comment]
I need to add some documentation and some settings here. You are right currently the rule is not `°C/2`.

If you go to the documentation to the python library I have developed and have used in this custom component (https://github.com/oncleben31/pypool-pump) you will discover I have implemented four different algorithms for computing the filtering duration in function of the temperatures (or even other parameters).

In the current version of the custom component I have chosen to use the abacus based algorithm only. The rule can be sum up by the blue line on this picture:
![Abacus f(T°C)](https://github.com/scadinot/pool/blob/master/docs/images/filtration_courbe.png?raw=true)

I have plan to add a way to chose the algorithm in a future version.

**Comment by mycanaletto** [comment]
Cool, I hope quickly ;-)

Thanks

**Comment by roumano** [comment]
Hi,
not sure if it's the good place for this request , but about filtration time, ideally, if it's temperature is going too low, a protection over the freeze with be great.

**Comment by oncleben31** [comment]
I have to check but I think the algorithm will ignore any temperature under 10°C. And I plan to add a winter mode to filter few hours in the coldest hours.

**Comment by plouf34** [comment]
Hello
Any news regarding winter mode or time filtration for temperature under 10°C?

**Comment by roumano** [comment]
> Hello Any news regarding winter mode or time filtration for temperature under 10°C?

This issue is closed, so it's maybe a better idea to create a new issue or add your comment on this opened ticket : #28
