### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'pool_pump'

### ISSUE THREAD

**Issue by roumano** [oncleben31/ha-pool_pump#16]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
the newest version of HomeAssistant 2021.5, give a BIG warning about missing `version` key of this integration and will be disabled in the next version with it !

## Debug log

```text

ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'pool_pump'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'pool_pump'

```

**Comment by g4seb** [comment]
@roumano , hi sorry i don't understand what did i do to fix it ?

Salut, désolé mais je ne comprends pas ce que je dois faire pour fixer l'erreur.

**Comment by roumano** [comment]
https://github.com/oncleben31/ha-pool_pump/pull/20/files
