### ISSUE TITLE
Pump start/stop every 5min

### ISSUE THREAD

**Issue by g4seb** [oncleben31/ha-pool_pump#22]
Bonsoir, ma filtration s'arrête et redémarre toutes les 5min. Je ne comprends pas pourquoi. 5 me n à votre n et 5min à off, puis 5 on, 5 off....

Hi, my pump stop and restart every 5min. I don't know why. 5 min on , 5 min off, and again...

Could you help me please.

**Comment by g4seb** [comment]
vu que c'est à chaque fois que le service pool pump check est appelé que la pompe s'éteint et au tour suivant, se rallume, ça serait pas dû au fait que ma commande est impulsionnel sur ma pompe ?? Et que lui il renvoie un ordre de marche, mais que moi forcément ça permute ?

**Comment by g4seb** [comment]
C'est bon j'ai trouvé. C'était bien la gestion sur front montant qui me faisait un bug

**Comment by oncleben31** [comment]
Je suis pas sur de comprendre. Faut il corriger quelque chose dans l'intégration ?

**Comment by g4seb** [comment]
> Je suis pas sur de comprendre. Faut il corriger quelque chose dans l'intégration ?

Bonjour, non. En fait j'ai un fonction sur front montant sur ma pompe. Et donc toutes les 5 minutes, elle faisait marche/arrêt et ainsi de suite. Je suis passé par un switch et cela règle le problème.
