### ISSUE TITLE
question for the futur

### ISSUE THREAD

**Issue by foXaCe** [oncleben31/ha-pool_pump#25]
Hello,

Is an update for this great project planned?
With maybe a config flow integration to help newbies more easily use this component
Anyway, thank you and bravo for this integration, I have been using it for two years.

**Comment by oncleben31** [comment]
Not really planned. I have lot of improvement ideas but missing time.
And as it's not broken, nothing push me to put it a the top of priority list.

I'm open to contributions or even open discussion on how to improve it.

**Comment by oncleben31** [comment]
I will perhpas invest some energy in a near future. I note your ideas don't hesitate to push new ones in the #27 issue.
