### ISSUE TITLE
auto-auto

### ISSUE THREAD

**Issue by foXaCe** [oncleben31/ha-pool_pump#8]
J'utilise ton component depuis plusieurs jours est-il marche très bien.
J’aimerai que home assistant vérifie tous les jours à 22h00 qu’il soit bien sur auto et que si ce n’est pas le cas qu’il le passe en Auto.
comment je pourrai faire ?

**Comment by oncleben31** [comment]
Une automation avec un trigger sur l'heure, une condition sur l'etat de l'input_select select et une action pour changer l'état de l'imput _select devrait faire le taf.

**Comment by foXaCe** [comment]
nickel super ça marche

merci
